### ISSUE TITLE
Comments on the initial run

### ISSUE THREAD

**Issue by nazirahmk** [MASILab/ADSP_AutoQA#1]
Great job! Here are my comments:

- The page seems need to be enlarge manually (but I believe it's just once, so no big deal)
![AutoQA](https://github.com/user-attachments/assets/08c79be7-c764-49d8-aad5-4fe68d572602)
- JSON file is not accessible: 
```
PermissionError: [Errno 13] Permission denied: '/nfs2/harmonization/ADSP_QA/BIOCARD/WMAtlasEVE3/QA.json'
```
- When I refresh let say (trying to emulate in case I restart the browser or just need to refresh), everything went back to 'Yes'. Possibly because of above issue. If I just go back and forward during the same run, the note and 'No' stays there. I think you read the json to generate the whole html after restart/refresh? 
- General run: takes about less than 2 minutes for 200 pngs WMAtlasEVE3 if there's no `No` or `Maybe` with manual right arrow press. Additional time will affect with more images (like PreQual, BISCUIT, fspecial will have multiple pages in one png) and adding comments when there are problematic figures.

**Comment by mkim-MASI** [comment]
1. You should just be able to zoom in like any other webpage so that the picture is not so small
2. I will change the permissions for the folders and files to be 775 and p_masi
3. Yes, it should be because of the above issue. After I change the permissions, let me know if this is still the case
4. If you want to go REALLY fast, just hold down the right arrow button. If that is too fast, but the current montage speed is too slow, let me know and I can either increase the montage speed or add an option to change the speed.

Thank you so much for your feedback, Nazirah!
